"""Deterministic expansion operator for the prototype."""

from __future__ import annotations

import uuid

from .executor_adapter import ExpansionRequest, ExecutorAdapter, validate_executor_children
from .models import DTERunSpec, SearchNode


_VARIANTS = [
    ("Assumption stress test", "Probe the weakest hidden assumption and look for counterexamples."),
    ("Constructive route", "Turn the claim into an explicit construction or derivation path."),
    ("Alternative formalism", "Re-express the idea in a different mathematical or physical formalism."),
    ("Boundary case analysis", "Analyze limiting cases where the claim may fail or become clearer."),
    ("Synthesis bridge", "Connect this node with neighboring directions to prepare a merge."),
]


def expand_node(parent: SearchNode, count: int, iteration: int) -> list[SearchNode]:
    """Generate child nodes for one parent.

    Real executor adapters can replace this with Codex/Kimi episodes. The output
    contract remains SearchNode.
    """

    children: list[SearchNode] = []
    for i in range(max(0, count)):
        label, instruction = _VARIANTS[i % len(_VARIANTS)]
        child = SearchNode(
            node_id=str(uuid.uuid4()),
            node_type="candidate",
            claim=f"{parent.claim} — {label}",
            rationale=f"{instruction} Parent rationale: {parent.rationale}".strip(),
            assumptions=list(parent.assumptions),
            evidence=list(parent.evidence),
            risks=list(parent.risks) + (["generated by deterministic prototype executor"] if i == 0 else []),
            parent_ids=[parent.node_id],
            confidence=max(0.05, min(0.95, parent.confidence - 0.03 + 0.02 * i)),
            status="frontier",
        )
        children.append(child)
    return children


def expand_frontier(
    nodes: list[SearchNode],
    budgets: dict[str, int],
    iteration: int,
    spec: DTERunSpec | None = None,
    executor_adapter: ExecutorAdapter | None = None,
) -> list[SearchNode]:
    """Close expanded parents and append their children."""

    by_id = {n.node_id: n for n in nodes}
    new_children: list[SearchNode] = []
    for node_id, budget in budgets.items():
        parent = by_id.get(node_id)
        if parent is None or parent.status != "frontier" or budget <= 0:
            continue
        if executor_adapter is None:
            children = expand_node(parent, budget, iteration=iteration)
        else:
            request = ExpansionRequest(parent=parent, count=budget, iteration=iteration, spec=spec)
            children = validate_executor_children(parent, budget, executor_adapter.expand(request))
        new_children.extend(children)
        parent.status = "closed"
        parent.expansion_budget = 0
    return nodes + new_children
