"""Expansion operator for the prototype.

The default expansion is deterministic and offline. A real Codex/Kimi/OpenClaw
executor can be plugged in through the adapter boundary, but it still returns
validated SearchNode children to DTE.
"""

from __future__ import annotations

import uuid
from collections.abc import Callable

from .adapter import ExecutorAdapter, validate_search_node_output
from .episode_adapter import (
    AgentEpisodeAdapter,
    LegacyExecutorEpisodeAdapter,
    build_executor_episode_request,
    run_and_commit_episode,
)
from .episode_commit import EpisodeGraph
from .models import DTERunSpec, ExpansionRequest, SearchNode
from .telemetry import EpisodeEventLog


_VARIANTS = [
    ("Assumption stress test", "Probe the weakest hidden assumption and look for counterexamples."),
    ("Constructive route", "Turn the claim into an explicit construction or derivation path."),
    ("Alternative formalism", "Re-express the idea in a different mathematical or physical formalism."),
    ("Boundary case analysis", "Analyze limiting cases where the claim may fail or become clearer."),
    ("Synthesis bridge", "Connect this node with neighboring directions to prepare a merge."),
]


def deterministic_expand_node(parent: SearchNode, count: int, iteration: int) -> list[SearchNode]:
    """Generate child nodes for one parent without external calls."""

    children: list[SearchNode] = []
    for i in range(max(0, count)):
        label, instruction = _VARIANTS[i % len(_VARIANTS)]
        child = SearchNode(
            node_id=str(uuid.uuid4()),
            node_type="candidate",
            claim=f"{parent.claim} — {label}",
            rationale=f"{instruction} Parent rationale: {parent.rationale}".strip(),
            assumptions=list(parent.assumptions),
            evidence=list(parent.evidence),
            risks=list(parent.risks) + (["generated by deterministic prototype executor"] if i == 0 else []),
            parent_ids=[parent.node_id],
            confidence=max(0.05, min(0.95, parent.confidence - 0.03 + 0.02 * i)),
            status="frontier",
        )
        children.append(child)
    return children


def expand_node(
    parent: SearchNode,
    count: int,
    iteration: int,
    spec: DTERunSpec | None = None,
    executor_adapter: ExecutorAdapter | None = None,
) -> list[SearchNode]:
    """Generate children for one parent through DTE's expansion boundary.

    If an external adapter is supplied, it receives a validated ExpansionRequest
    and must return SearchNode children. Otherwise, deterministic local expansion
    is used for tests and offline protocol validation.
    """

    if count <= 0:
        return []
    if executor_adapter is None:
        return deterministic_expand_node(parent, count=count, iteration=iteration)
    request = ExpansionRequest(parent=parent, child_count=count, iteration=iteration, spec=spec)
    if hasattr(executor_adapter, "expand"):
        children = executor_adapter.expand(request)  # type: ignore[union-attr]
    else:
        children = executor_adapter(request)
    return validate_search_node_output(parent, count, children)


def expand_frontier(
    nodes: list[SearchNode],
    budgets: dict[str, int],
    iteration: int,
    spec: DTERunSpec | None = None,
    executor_adapter: ExecutorAdapter | None = None,
    episode_adapter: AgentEpisodeAdapter | None = None,
    episode_graph: EpisodeGraph | None = None,
    episode_event_log: EpisodeEventLog | None = None,
    run_id: str = "local-run",
    after_node_expanded: Callable[[list[SearchNode]], bool] | None = None,
) -> list[SearchNode]:
    """Close expanded parents and append their children."""

    graph = episode_graph or EpisodeGraph(nodes=list(nodes))
    if episode_adapter is not None and executor_adapter is not None:
        raise ValueError("provide either episode_adapter or executor_adapter, not both")
    effective_episode_adapter = episode_adapter
    if effective_episode_adapter is None and executor_adapter is not None:
        effective_episode_adapter = LegacyExecutorEpisodeAdapter(executor_adapter)
    new_children: list[SearchNode] = []
    for node_id, budget in budgets.items():
        parent = graph.node_by_id(node_id)
        if parent is None or parent.status != "frontier" or budget <= 0:
            continue
        if effective_episode_adapter is None:
            validated_children = expand_node(parent, budget, iteration=iteration, spec=spec)
            new_children.extend(validated_children)
            parent.status = "closed"
            parent.expansion_budget = 0
            graph.nodes.extend(validated_children)
        else:
            request = build_executor_episode_request(
                graph,
                parent,
                run_id=run_id,
                iteration=iteration,
                max_returned_children=budget,
                objective=(parent.claim if spec is None else f"{spec.goal}: expand {parent.claim}"),
                constraints=[] if spec is None else list(spec.constraints),
                native_orchestration_allowed=True if spec is None else spec.allow_self_organized_executor,
            )
            outcome = run_and_commit_episode(
                graph,
                request,
                effective_episode_adapter,
                telemetry=episode_event_log,
            )
            if not outcome.accepted:
                raise ValueError(outcome.rejection_reason or "Executor episode result rejected")
            new_children.extend(
                node for node in graph.nodes if node.node_id in set(outcome.accepted_node_ids)
            )
        # This callback is the interruption safe point: the oracle has returned,
        # its complete output has passed the Executor guard, and the node-level
        # result has been committed. A pending request cannot bypass validation.
        if after_node_expanded is not None and after_node_expanded(graph.nodes):
            break
    return graph.nodes
