"""Expansion operator for the prototype.

The default expansion is deterministic and offline. A real Codex/Kimi/OpenClaw
executor can be plugged in through the adapter boundary, but it still returns
validated SearchNode children to DTE.
"""

from __future__ import annotations

import uuid
from collections.abc import Callable

from .adapter import ExecutorAdapter, validate_adapter_output
from .models import DTERunSpec, ExpansionRequest, SearchNode


_VARIANTS = [
    ("Assumption stress test", "Probe the weakest hidden assumption and look for counterexamples."),
    ("Constructive route", "Turn the claim into an explicit construction or derivation path."),
    ("Alternative formalism", "Re-express the idea in a different mathematical or physical formalism."),
    ("Boundary case analysis", "Analyze limiting cases where the claim may fail or become clearer."),
    ("Synthesis bridge", "Connect this node with neighboring directions to prepare a merge."),
]


def deterministic_expand_node(parent: SearchNode, count: int, iteration: int) -> list[SearchNode]:
    """Generate child nodes for one parent without external calls."""

    children: list[SearchNode] = []
    for i in range(max(0, count)):
        label, instruction = _VARIANTS[i % len(_VARIANTS)]
        child = SearchNode(
            node_id=str(uuid.uuid4()),
            node_type="candidate",
            claim=f"{parent.claim} — {label}",
            rationale=f"{instruction} Parent rationale: {parent.rationale}".strip(),
            assumptions=list(parent.assumptions),
            evidence=list(parent.evidence),
            risks=list(parent.risks) + (["generated by deterministic prototype executor"] if i == 0 else []),
            parent_ids=[parent.node_id],
            confidence=max(0.05, min(0.95, parent.confidence - 0.03 + 0.02 * i)),
            status="frontier",
        )
        children.append(child)
    return children


def expand_node(
    parent: SearchNode,
    count: int,
    iteration: int,
    spec: DTERunSpec | None = None,
    executor_adapter: ExecutorAdapter | None = None,
) -> list[SearchNode]:
    """Generate children for one parent through DTE's expansion boundary.

    If an external adapter is supplied, it receives a validated ExpansionRequest
    and must return SearchNode children. Otherwise, deterministic local expansion
    is used for tests and offline protocol validation.
    """

    if count <= 0:
        return []
    if executor_adapter is None:
        return deterministic_expand_node(parent, count=count, iteration=iteration)
    request = ExpansionRequest(parent=parent, child_count=count, iteration=iteration, spec=spec)
    if hasattr(executor_adapter, "expand"):
        children = executor_adapter.expand(request)  # type: ignore[union-attr]
    else:
        children = executor_adapter(request)
    return validate_adapter_output(parent, count, {"nodes": [child.model_dump() for child in children]})


def expand_frontier(
    nodes: list[SearchNode],
    budgets: dict[str, int],
    iteration: int,
    spec: DTERunSpec | None = None,
    executor_adapter: ExecutorAdapter | None = None,
    after_node_expanded: Callable[[list[SearchNode]], bool] | None = None,
) -> list[SearchNode]:
    """Close expanded parents and append their children."""

    by_id = {n.node_id: n for n in nodes}
    new_children: list[SearchNode] = []
    for node_id, budget in budgets.items():
        parent = by_id.get(node_id)
        if parent is None or parent.status != "frontier" or budget <= 0:
            continue
        new_children.extend(
            expand_node(
                parent,
                budget,
                iteration=iteration,
                spec=spec,
                executor_adapter=executor_adapter,
            )
        )
        parent.status = "closed"
        parent.expansion_budget = 0
        if after_node_expanded is not None and after_node_expanded(nodes + new_children):
            break
    return nodes + new_children
